name: Diagnostico de Pastas

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo do projeto
        uses: actions/checkout@v4

      # Esse comando vai nos mostrar exatamente onde está o pubspec.yaml
      - name: Escanear todas as pastas do repositorio
        run: |
          echo "=== ONDE ESTOU ==="
          pwd
          echo "=== LISTA DE ARQUIVOS NA RAIZ ==="
          ls -la
          echo "=== BUSCANDO PUBSPEC.YAML EM TODO LUGAR ==="
          find . -name "pubspec.yaml"
