name: Gerar APK do Racha

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do seu repositório (os arquivos já estão na raiz)
      - name: Baixar codigo do projeto
        uses: actions/checkout@v4

      # 2. Configura o Java na máquina virtual
      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Configura o Flutter estável na máquina virtual
      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'

      # 4. Baixa todas as dependências direto na raiz
      - name: Baixar dependencias do App
        run: flutter pub get

      # 5. Compila o código e gera o APK final
      - name: Fabricar APK Release
        run: flutter build apk --release

      # 6. Salva o APK pronto localizado na raiz do build
      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: Racha_da_Resenha_APK
          path: build/app/outputs/flutter-apk/app-release.apk
